name: franklab_nwb_extensions
channels:
- defaults
- conda-forge
- anaconda
dependencies:
- "python >= 3.6"
- pynwb
- hdmf
- sphinx
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
